name: "Security Scanning"
on:
  workflow_call:
jobs:
  ShiftLeft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
    - name: Upload report
      uses: github/codeql-action/upload-sarif@a09933a12a80f87b87005513f0abb1494c27a716 # v2.21.4
      with:
        sarif_file: reports

  Checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Perform Checkov Scan
      uses: bridgecrewio/checkov-action@v12
      with:
        output_format: cli,sarif
        output_file_path: console,results.sarif
        skip_check: CKV2_GHA_1
        
    - name: Upload Report
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: results.sarif
